#!/usr/bin/env bash

usage() {
    echo "Usage: gh action-usage <repo>"
}

if [ $# -ne 1 ]; then
    usage >&2
    exit 1
fi

repo="${1}"

gh api -X GET search/code -f q="$repo path:.github/workflows/ language:YAML fork:true" --jq '.total_count'
