name: gh-action-usage
on: [push]
jobs:
  gh-action-usage-on-os:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: test
        uses: ./
        with:
          repository: ${{ github.repository }}
      - run: echo "This repository is used ${{ steps.test.outputs.usage-count }} times"
        shell: bash

  gh-action-usage-release:
    runs-on: ubuntu-latest
    needs: gh-action-usage-on-os
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Release
      - name: Release that
        uses: rlespinasse/release-that@v1.x
    